# This is a basic workflow to help you get started with Actions

name: Deploy subfolder to heroku

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]

jobs:
    deploy-prod:
        runs-on: ubuntu-latest
        needs: test-unit
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2
            # possibly setup node action here...
            # possibly cache of node modules action here...
            # build steps here...
            - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
              with:
                  api_key: ${{secrets.HEROKU_API_KEY}}
                  email: ${{secrets.HEROKU_EMAIL}}
                  app_name: stuyspeccmsbackend
                  heroku_branch: "master"
                  subfolder: "server"
