on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "npm"
                  cache-dependency-path: client/package-lock.json
            - run: npm i -g vercel
            - name: "Upload build to production"
              env: { VERCEL_AUTH_TOKEN: "${{ secrets.VERCEL_AUTH_TOKEN }}" }
              run: vercel --prod --confirm --token $VERCEL_AUTH_TOKEN
